name = "julia-package-registry"
uuid = "24be385e-6baa-4bbc-9931-0f409b839c8e"
repo = "https://github.com/csiro-energy-systems/julia-package-registry.git"

[packages]
b2eb5e28-d000-4b93-8009-89b0f234afbb = { name = "MultiGigModel", path = "M/MultiGigModel" }
